const images = {
    Malaria:[
        require('../../assets/Yoga/Malaria/Shitalipranayama.jpg'),
        require('../../assets/Yoga/Malaria/Nadishodhanpranayama.jpg')
    ],
    DrugReaction:[
        require('../../assets/Yoga/DrugReaction/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/DrugReaction/BhastrikaPranayama.jpg'),
        require('../../assets/Yoga/DrugReaction/Bhramaripranayama.jpg'),
        require('../../assets/Yoga/DrugReaction/FishPose.jpg'),
        require('../../assets/Yoga/DrugReaction/Nadishodhanpranayama.jpg') 
    ],
    Allergy:[
        require('../../assets/Yoga/Allergy/CrescentLunge.jpg'),
        require('../../assets/Yoga/Allergy/Matsyasana.jpg'),
        require('../../assets/Yoga/Allergy/ShoulderStand.jpg')
    ],
    Hypothyroidism:[
        require('../../assets/Yoga/Hypothyroidism/Dhanurasana.jpg'),
        require('../../assets/Yoga/Hypothyroidism/Dhanurasana.jpg'),
        require('../../assets/Yoga/Hypothyroidism/Halasana.jpg'),
        require('../../assets/Yoga/Hypothyroidism/Matsyasana.jpg'),
        require('../../assets/Yoga/Hypothyroidism/SetuBandhasana.jpg')
    ],
    Psoriasis:[
        require('../../assets/Yoga/Psoriasis/Balasana.jpg'),
        require('../../assets/Yoga/Psoriasis/BreathingExercises.jpg'),
        require('../../assets/Yoga/Psoriasis/SalutationSeal.jpg')
    ],
    GERD: [
        require('../../assets/Yoga/GERD/AgnisarKriya.jpg'),
        require('../../assets/Yoga/GERD/Kapalbhati.jpg'),
        require('../../assets/Yoga/GERD/Marjariasana.jpg')
    ],
    Chroniccholestasis:[
        require('../../assets/Yoga/Chroniccholestasis/Bhujangasana.jpg'),
        require('../../assets/Yoga/Chroniccholestasis/Padangusthasana.jpg'),
        require('../../assets/Yoga/Chroniccholestasis/ParipurnaNavasana.jpg')
    ],
    hepatitisA: [
        require('../../assets/Yoga/hepatitisA/AdhoMukhiMarjariAsana.jpg'),
        require('../../assets/Yoga/hepatitisA/Marjariasana.jpg'),
        require('../../assets/Yoga/hepatitisA/Shitalipranayama.jpg')
    ],
    Osteoarthristis: [
        require('../../assets/Yoga/Osteoarthristis/HalfmoonPose.jpg'),
        require('../../assets/Yoga/Osteoarthristis/MountainPose.jpg'),
        require('../../assets/Yoga/Osteoarthristis/SeatedWarrior1.jpg')
    ],
    vertigoParoymsalPositionalVertigo: [
        require('../../assets/Yoga/vertigoParoymsalPositionalVertigo/Halasana.jpg'),
        require('../../assets/Yoga/vertigoParoymsalPositionalVertigo/Nadishodhanpranayama.jpg'),
        require('../../assets/Yoga/vertigoParoymsalPositionalVertigo/SalambaSirsasana.jpg'),
        require('../../assets/Yoga/vertigoParoymsalPositionalVertigo/ShanmukhiMudra.png')
    ],
    Hypoglycemia: [
        require('../../assets/Yoga/Hypoglycemia/BowPose.jpg'),
        require('../../assets/Yoga/Hypoglycemia/Supinespinaltwist.jpg'),
        require('../../assets/Yoga/Hypoglycemia/UpwardFacingDog.jpg')
    ],
    Acne: [
        require('../../assets/Yoga/Acne/Headstandbackwardbends.jpg'),
        require('../../assets/Yoga/Acne/hiddenlotus.jpg'),
        require('../../assets/Yoga/Acne/Sarvangasana.jpg')
    ],
    Diabetes: [
        require('../../assets/Yoga/Diabetes/Plowpose.jpg'),
        require('../../assets/Yoga/Diabetes/RecliningBoundAnglePose.jpg'),
        require('../../assets/Yoga/Diabetes/Seatedforwardbend.jpg')
    ],
    Hypertension: [
        require('../../assets/Yoga/Hypertension/Balasana.jpg'),
        require('../../assets/Yoga/Hypertension/Cobrapose.jpg'),
        require('../../assets/Yoga/Hypertension/Sukhasana.jpg')
    ],
    Pepticulcerdiseae: [
        require('../../assets/Yoga/Pepticulcerdiseae/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/Pepticulcerdiseae/BhastrikaPranayama.jpg'),
        require('../../assets/Yoga/Pepticulcerdiseae/Bhramaripranayama.jpg')
    ],
    Dimorphichemmorhoidspiles: [
        require('../../assets/Yoga/Dimorphichemmorhoidspiles/AdhoMukhiMarjariAsana.jpg'),
        require('../../assets/Yoga/Dimorphichemmorhoidspiles/ArdhaMatsyendrasana.jpg'),
        require('../../assets/Yoga/Dimorphichemmorhoidspiles/Janusirasana.jpg'),
        require('../../assets/Yoga/Dimorphichemmorhoidspiles/Sarvangasana.jpg')
    ],
    CommonCold:[
        require('../../assets/Yoga/CommonCold/UpavisthaKonasana.jpg'),
        require('../../assets/Yoga/CommonCold/Uttanasana.jpg'),
        require('../../assets/Yoga/CommonCold/ViparitaKarani.png')
    ],
    Cervicalspondylosis:[
        require('../../assets/Yoga/Cervicalspondylosis/ArdhaMatsyendrasana.jpg'),
        require('../../assets/Yoga/Cervicalspondylosis/Cobrapose.jpg'),
        require('../../assets/Yoga/Cervicalspondylosis/Dhanurasana.jpg')
    ],
    Urinarytractinfection:[
        require('../../assets/Yoga/Urinarytractinfection/BaddhaKonasana.png'),
        require('../../assets/Yoga/Urinarytractinfection/hiddenlotus.jpg'),
        require('../../assets/Yoga/Urinarytractinfection/Padangusthasana.jpg'),
        require('../../assets/Yoga/Urinarytractinfection/TittibhasanaFireflyPose.jpg')
    ],
    Varicoseveins:[
        require('../../assets/Yoga/Varicoseveins/Stretching.jpg')
    ],
    AIDS:[
        require('../../assets/Yoga/AIDS/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/AIDS/BhastrikaPranayama.jpg'),
        require('../../assets/Yoga/AIDS/Dandasana.jpg'),
        require('../../assets/Yoga/AIDS/Uttanasana.jpg')

    ],
    Paralysisbrainhemorrhage:[
        require('../../assets/Yoga/Paralysisbrainhemorrhage/Mandukasana.jpg'),
        require('../../assets/Yoga/Paralysisbrainhemorrhage/Parvatasana.jpg'),
        require('../../assets/Yoga/Paralysisbrainhemorrhage/Siddhasana.jpg'),
        require('../../assets/Yoga/Paralysisbrainhemorrhage/Veerasana.jpg')
    ],
    HepatitisB:[
        require('../../assets/Yoga/HepatitisB/ArdhaMatsyendrasana.jpg'),
        require('../../assets/Yoga/HepatitisB/FishPose.jpg'),
        require('../../assets/Yoga/HepatitisB/Shalabasana.jpg')
    ],
    Fungalinfection:[
        require('../../assets/Yoga/Fungalinfection/Marichyasana.jpg'),
        require('../../assets/Yoga/Fungalinfection/StandingBigToePose.jpg'),
        require('../../assets/Yoga/Fungalinfection/SuptaBaddhaKonasana.jpg')
    ],
    HepatitisC:[
        require('../../assets/Yoga/HepatitisC/BreathingExercises.jpg'),
        require('../../assets/Yoga/HepatitisC/Marjariasana.jpg'),
        require('../../assets/Yoga/HepatitisC/Shitalipranayama.jpg'),

    ],
    Migraine:[
        require('../../assets/Yoga/Migraine/Hastapadasana.jpg'),
        require('../../assets/Yoga/Migraine/Marjariasana.jpg'),
        require('../../assets/Yoga/Migraine/SetuBandhasana.jpg')
    ],
    BronchialAsthma:[
        require('../../assets/Yoga/BronchialAsthma/BaddhaKonasana.png'),
        require('../../assets/Yoga/BronchialAsthma/Dhanurasana.jpg'),
        require('../../assets/Yoga/BronchialAsthma/Ustrasana.jpg')
    ],
    Alcoholichepatitis:[
        require('../../assets/Yoga/Alcoholichepatitis/Bhujangasana.jpg'),
        require('../../assets/Yoga/Alcoholichepatitis/Padangusthasana.jpg'),
        require('../../assets/Yoga/Alcoholichepatitis/ParipurnaNavasana.jpg'),
        require('../../assets/Yoga/Alcoholichepatitis/Marjariasana.jpg')
    ],
    Jaundice:[
        require('../../assets/Yoga/Jaundice/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/Jaundice/Bhramaripranayama.jpg'),
        require('../../assets/Yoga/Jaundice/KapalBhati.jpg')
    ],
    HepatitisE:[
        require('../../assets/Yoga/HepatitisE/Shitalipranayama.jpg'),
        require('../../assets/Yoga/HepatitisE/Marjariasana.jpg'),
        require('../../assets/Yoga/HepatitisE/Shalabasana.jpg')
    ],
    Dengue:[
        require('../../assets/Yoga/Dengue/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/Dengue/Nadishodhanpranayama.jpg'),
        require('../../assets/Yoga/Dengue/KapalBhati.jpg')
    ],
    HepatitisD:[
        require('../../assets/Yoga/HepatitisD/BreathingExercises.jpg'),
        require('../../assets/Yoga/HepatitisD/Shalabasana.jpg'),
        require('../../assets/Yoga/HepatitisD/Marjariasana.jpg')
    ],
    Heartattack:[
        require('../../assets/Yoga/Heartattack/ArdhaMatsyendrasana.jpg'),
        require('../../assets/Yoga/Dengue/AnulomaVilomaPranayama.jpg'),
        require('../../assets/Yoga/Heartattack/BreathingExercises.jpg'),
        require('../../assets/Yoga/Heartattack/Meditation.jpg')
    ],
    Pneumonia:[
        require('../../assets/Yoga/Pneumonia/Bhujangasana.jpg'),
        require('../../assets/Yoga/Pneumonia/Marjariasana.jpg'),
        require('../../assets/Yoga/Pneumonia/Padangusthasana.jpg')
    ],
    Arthritis:[
        require('../../assets/Yoga/Arthritis/Ashtangayoga.png'),
        require('../../assets/Yoga/Arthritis/Vinyasayoga.jpg'),
        require('../../assets/Yoga/Arthritis/walkingbicyclingswimming.png')
    ],
    Gastroenteritis:[
        require('../../assets/Yoga/Gastroenteritis/Balasana.jpg'),
        require('../../assets/Yoga/Gastroenteritis/Padahastasana.jpg'),
        require('../../assets/Yoga/Gastroenteritis/Vajrasana.jpg')
    ],
    Tuberculosis:[
        require('../../assets/Yoga/Tuberculosis/Tadasana.jpg'),
        require('../../assets/Yoga/Tuberculosis/BhastrikaPranayama.jpg'),
        require('../../assets/Yoga/Tuberculosis/KapalBhati.jpg'),
        require('../../assets/Yoga/Tuberculosis/Trikonasana.jpg')
    ]
}

export default images;